### ISSUE TITLE
Dane 404

### ISSUE THREAD

**Issue by KGrzeg** [yasiupl/nadajniki#2]
Adres do danych z pliku `readme.md` (https://dane.gov.pl/dataset/1070/resource/18769) przenosi na stronę, która zwraca błąd 404.

**Comment by yasiupl** [comment]
Widocznie zasób został usunięty, jako że UKE publikuje nowe dane co miesiąc. W readme.md dodam link do zbioru danych https://dane.gov.pl/dataset/1070
