### ISSUE TITLE
Aktualne dane

### ISSUE THREAD

**Issue by panjakub** [yasiupl/nadajniki#61]
Cześć, 

zrobiłem plik, który będzie się aktualizował razem z wykazem z UKE. Jakbyś chciał skorzystać, żeby mapka się częściej aktualizowała, to jest dostępny pod [http://ham.infozin.net/opendata/](http://ham.infozin.net/opendata/).
Najnowszy plik zawsze będzie ten sam, w następnych iteracjach będzie przenoszony do archiwum i aktualizowany. 

Jeśli nadal masz ochotę to rozwijać, to zapraszam do używania. :) 

Pozdr

**Comment by mattimac** [comment]
Mamy już aktualizację danych na stronie UKE w xls a plik jest nieaktualny. Poruszyłem w UKE i w innym issue, proponuję porzucić ten pomysł i zamknąć.
